//
//  LoginWorker.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 11/8/17.
//  Copyright (c) 2017 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
  func doSomeWork()
  {
  }
}
