//
//  LoginModels.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 11/8/17.
//  Copyright (c) 2017 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum InitiateLogIn
  {
    struct Request
    {
      var userId: String
      var password: String
    }
    struct Response
    {
      var responseModel: LoginResponseModel
    }
    struct ViewModel
    {
      struct DisplayableResponse {
        var token: String
      }
      var displayedResponse: DisplayableResponse
    }
    
  }
}
