//
//  LoginInteractor.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 11/8/17.
//  Copyright (c) 2017 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func loginWithRequest(request: Login.InitiateLogIn.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var authenticationWorker = AuthenticationWorker(authenticationService: LoginService())
  
  // MARK: LoginWithRequest
  
  func loginWithRequest(request: Login.InitiateLogIn.Request)
  {
    //make login request
    authenticationWorker.initiateLoginProcess(withCredentials: request) { (responseModel, error) in
      if let responseModel = responseModel {
        let loginResponse = Login.InitiateLogIn.Response(responseModel: responseModel)
        self.presenter?.presentLoginResponseModel(response: loginResponse)
      }else {
        self.presenter?.presentError(error: error!)
      }
      
    }
  }
  
  
}
