//
//  LoginPresenter.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 11/8/17.
//  Copyright (c) 2017 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentLoginResponseModel(response: Login.InitiateLogIn.Response)
  func presentError(error: Error)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentLoginResponseModel(response: Login.InitiateLogIn.Response)
  {
    //make view model from response model
    let displayedModel = Login.InitiateLogIn.ViewModel.DisplayableResponse(firstName: response.responseModel.firstName, lastName: response.responseModel.lastName)
    let viewModel = Login.InitiateLogIn.ViewModel(displayedResponse: displayedModel)
    viewController?.displayLoginResult(viewModel: viewModel)
  }
  
  func presentError(error: Error)
  {
    viewController?.presentError(error: error)
  }
  
}
