//
//  LoginViewController.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 11/8/17.
//  Copyright (c) 2017 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
  func displayLoginResult(viewModel: Login.InitiateLogIn.ViewModel)
  func presentError(error: Error)
}

class LoginViewController: UITableViewController, LoginDisplayLogic
{
  var interactor: LoginBusinessLogic?
  var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?

  //MARK: - Reference Outlets
  @IBOutlet weak var loginImageView: UIImageView!
  @IBOutlet weak var emailAddressTextField: UITextField!
  @IBOutlet weak var passwordTextField: UITextField!
  @IBOutlet weak var loginButton: UIButton!
  @IBOutlet weak var forgotPasswordButton: UIButton!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func initiateLoginProcess()
  {
    let userId = self.emailAddressTextField.text!
    let password = self.passwordTextField.text!
    let request = Login.InitiateLogIn.Request(userId: userId, password: password)
    interactor?.loginWithRequest(request: request)
    UIApplication.shared.isNetworkActivityIndicatorVisible = true
  }
  
  func displayLoginResult(viewModel: Login.InitiateLogIn.ViewModel)
  {
    UIApplication.shared.isNetworkActivityIndicatorVisible = false
    print("\(viewModel.displayedResponse.firstName) \(viewModel.displayedResponse.lastName)")
    performSegue(withIdentifier: "LandingScene", sender: self)
  }
  
  func presentError(error: Error)
  {
    UIApplication.shared.isNetworkActivityIndicatorVisible = false
    print("\(error.localizedDescription)")
  }
  
  // MARK: - Action Methods
  @IBAction func loginButtonAction(_ sender: UIButton) {
    print("login button action")
    initiateLoginProcess()
  }
  
  @IBAction func forgotPasswordButtonAction(_ sender: UIButton) {
    print("forgot password button action")
  }
  
  @IBAction func signUpButtonAction(_ sender: UIButton) {
    print("sign up button action")
  }
  ///
  
  override func shouldPerformSegue(withIdentifier identifier: String, sender: Any?) -> Bool {
    return false
  }
  
}
