//
//  LandingSceneVCModels.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 3/6/18.
//  Copyright (c) 2018 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LandingSceneVC
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
    
  enum UserDetail
  {
    struct Response
    {
        var response: User?
    }
    struct ViewModel
    {
        var userInfo: User
    }
  }
    
}
