//
//  LandingSceneVCRouter.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 3/6/18.
//  Copyright (c) 2018 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LandingSceneVCRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LandingSceneVCDataPassing
{
  var dataStore: LandingSceneVCDataStore? { get }
}

class LandingSceneVCRouter: NSObject, LandingSceneVCRoutingLogic, LandingSceneVCDataPassing
{
  weak var viewController: LandingSceneViewController?
  var dataStore: LandingSceneVCDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: LandingSceneVCViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: LandingSceneVCDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
