//
//  LandingSceneVCPresenter.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 3/6/18.
//  Copyright (c) 2018 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingSceneVCPresentationLogic
{
  func presentSomething(response: LandingSceneVC.Something.Response)
  func presentRequestForUserInformation(response: LandingSceneVC.UserDetail.Response)
}

class LandingSceneVCPresenter: LandingSceneVCPresentationLogic
{
  weak var viewController: LandingSceneVCDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LandingSceneVC.Something.Response)
  {
    let viewModel = LandingSceneVC.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
  func presentRequestForUserInformation(response: LandingSceneVC.UserDetail.Response)
  {
    if let userData = response.response {
      let viewModel = LandingSceneVC.UserDetail.ViewModel(userInfo: userData)
      viewController?.displayUserInformation(viewModel: viewModel)
    }
  }
    
    
    
}
