//
//  LandingSceneVCInteractor.swift
//  ProjectWLT
//
//  Created by Saleh Masum on 3/6/18.
//  Copyright (c) 2018 Selise. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingSceneVCBusinessLogic
{
  func doSomething(request: LandingSceneVC.Something.Request)
  func showRequestForUserInformation()
}

protocol LandingSceneVCDataStore
{
    var userDetail: User? { get set }
}

class LandingSceneVCInteractor: LandingSceneVCBusinessLogic, LandingSceneVCDataStore
{
  var presenter: LandingSceneVCPresentationLogic?
  var worker: LandingSceneVCWorker?
  //var name: String = ""
  
  // MARK: Do something
  var userDetail: User?
  
  func doSomething(request: LandingSceneVC.Something.Request)
  {
    worker = LandingSceneVCWorker()
    worker?.doSomeWork()
    
    let response = LandingSceneVC.Something.Response()
    presenter?.presentSomething(response: response)
  }
    
  func showRequestForUserInformation() {
    let response = LandingSceneVC.UserDetail.Response(response: self.userDetail)
    presenter?.presentRequestForUserInformation(response: response)
  }
    
}
